# -*- coding: utf-8 -*-
"""cs622_graph_plotting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EA1zjjQbshW_zbX5Ua5aAGhMeRy2obvQ
"""

import pandas as pd
import numpy as np

File_name = "cdf.csv"

df = pd.read_csv(File_name, header = None)
df

X = df.iloc[:,0].values
X

Y = df.iloc[:,1].values
Y

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

plt.plot(X,Y)
Title  = "Access distance Analysis"
plt.title(Title)
plt.xlabel("log10(distance)")
plt.ylabel("F(d) = n/N")
#plt.yticks(np.arange(0,1,0.2))
#plt.xticks(np.arange(1,6,0.5))
#plt.ylim([0.88,1])
#plt.xlim([0,6])
plt.savefig(Title + ".png")
